name: project64 # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Nintendo 64 emulator
description: |
   Nintendo 64 emulator

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  project64_icon.png
title: 1964 (Project64)

apps:
  project64:
    command: project64
parts:
  project64:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      project64: build/
      project64.1: man/man1/

architectures:
  - build-on: i386

